export type Sweetness = "dry-spicy" | "balanced-oak" | "honey-vanilla";

export interface Product {
  id: number;
  collection: string;
  name: string;
  price: number;
  age: number;
  sweetness: Sweetness;
  exclusivity: number;
  badge: { label: string; color: string } | null;
  src: string;
  description: string;
  nose: string;
  palate: string;
  finish: string;
  abv: string;
  barrel: string;
  origin: string;
  ageLabel: string;
}

export const ALL_PRODUCTS: Product[] = [
  {
    id: 1,
    collection: "Collection Prestige",
    name: "Dzama Cuvée Noire",
    price: 185,
    age: 20,
    sweetness: "honey-vanilla",
    exclusivity: 95,
    badge: { label: "Réserve Rare", color: "bg-secondary-container text-white" },
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDkNZZBhKWt910gPCY5ZMiKo7-alq4v2e3RJLfpHPgw02m-LzQ79UkN7rtiL6bnhu-IuC2EMpWAa0JDLJbDfm76xD-aCFHhRo1Wh057lqphxUDDqDdG6oVeaysSH4KzU8kQmE60jt1LVKjj7qUC0h3Tp-TPdhtT_p8uVOKjDTbp-5bCcutMX5d6S5DfKJWbbFR3Qh4iEHveG33mQ7QtMvXlbxu0_A9ctNKRv6DtqW5MlSNcB5zW14q-HbKGZGcKA0J9_eox15A-Ggw",
    description: "Un chef-d'œuvre de la distillation malgache, vieilli en fûts de chêne du Limousin carbonisés pour atteindre un profil d'une complexité inégalée et d'une douceur veloutée.",
    nose: "Vanille & Épices",
    palate: "Chêne Riche",
    finish: "Fumée Mielleuse",
    abv: "45% Alc/Vol",
    barrel: "Ex-Cognac, Chêne Limousin Français",
    origin: "Madagascar, Nosy Boraha",
    ageLabel: "Système Solera 20 Ans",
  },
  {
    id: 2,
    collection: "Série Millésimée",
    name: "Dzama Vanille 10 Yr",
    price: 82,
    age: 10,
    sweetness: "honey-vanilla",
    exclusivity: 70,
    badge: null,
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCmsAmKit2tv16XWqajWW01Qil4Xv1ELICN8IT2jGKVldvno0OSY_4_JNp7TsDehC65hhR396bLUh03nBCVmVnIuDgB2r1y5heuK5gEqfIXkMZgZZm4HDasAjZnirYQwiPzq1fTnIgY_knNWaDS9tau2s-QuGszXOPYoG-QSftOQnzD-J3W79M7qzgz6M5jxkO2pkd-SX7VIoMgviE5LJAi15W-5YtykdMEQA1byzraIXXpmdcMjsu4UewlskuqewXD3_6j0SL5s2Y",
    description: "Une décennie de maturation tropicale révèle un rhum généreux aux notes de vanille sauvage de l'île, d'une légèreté trompeuse et d'une longueur en bouche remarquable.",
    nose: "Vanille Sauvage",
    palate: "Miel & Bois Doux",
    finish: "Longue & Crémeuse",
    abv: "42% Alc/Vol",
    barrel: "Chêne Américain Ex-Bourbon",
    origin: "Madagascar, Côte Est",
    ageLabel: "10 Ans d'Âge",
  },
  {
    id: 3,
    collection: "Maître de Chai",
    name: "Dzama Millésime 1998",
    price: 425,
    age: 26,
    sweetness: "balanced-oak",
    exclusivity: 98,
    badge: { label: "Édition Limitée", color: "bg-primary-container text-on-primary" },
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCV-DJNDAVU7m7_DI4MFzbyWBPpJvtor47_xLAUverNZJpjLhy3zyxLjcoNT_jdMX2F3sTw5xYY-fhZmuP6zHMx0PidNbP5p_r-JzQAl-CuC4Azoo1jxOEhXod2m2URtAOBn0wjA1s3behpxWixHxGU1BmrGDtWluAoQY-DWzdZhL66wc_o5jLG3eFYcgdvMNdGxxPX_uuBh2wWeD2ynS6Rzp7qLFtzPZE07_ltBNJCx94G1xl7zpWqqDzTTaD4IIFqRX2Rz9bb3wk",
    description: "Né d'une récolte exceptionnelle, ce millésime 1998 incarne l'apogée du savoir-faire Dzama. Vingt-six ans d'affinage en cave révèlent une architecture de saveurs d'une profondeur vertigineuse.",
    nose: "Fruits Secs & Cuir",
    palate: "Épices & Cacao Noir",
    finish: "Boisée & Persistante",
    abv: "48% Alc/Vol",
    barrel: "Ex-Bourbon, Chêne Hongrois",
    origin: "Madagascar, Nosy Boraha",
    ageLabel: "Millésime 1998 — 26 Ans",
  },
  {
    id: 4,
    collection: "Édition des Fondateurs",
    name: "Dzama Vieux 6 Ans",
    price: 64,
    age: 6,
    sweetness: "dry-spicy",
    exclusivity: 60,
    badge: null,
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuA22PCQ3SKTx1e1KXfazbAI4oODcM7EZll37daPjtI8NA9G6N2G8B9N40f0kFqVzhx57w03M6EL26RMOjXzL5PyCZFe5iS6XmFnmcOcuEJHeGzZEtzo0f8lRjexhC3cR_UGwkEb2wjsSKUF8teFvLtTKxk9SjH9FEVBiWjDFdfOoZw8RNslNJ7Ra6IjpTkIzXQFNKBO4tLZb5vZvIJGu3ukFFc--R5jbQJc4SDOvWAqFV9Fckta2SRiKM8KN0EUs-yKhzVFwWos2TE",
    description: "Hommage direct à la vision originelle de Lucien Fohine, ce vieux rhum six ans exprime le caractère brut et sincère de la canne malgache, sec et rigoureusement épicé.",
    nose: "Canne Fraîche & Poivre",
    palate: "Sec & Boisé",
    finish: "Épicée & Franche",
    abv: "40% Alc/Vol",
    barrel: "Chêne du Limousin",
    origin: "Madagascar, Nord",
    ageLabel: "6 Ans d'Âge",
  },
  {
    id: 5,
    collection: "Exclusivité Distillerie",
    name: "Dzama Blanc Intense",
    price: 45,
    age: 3,
    sweetness: "dry-spicy",
    exclusivity: 50,
    badge: null,
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBa689rTgZodT0bdVrPmDmGecS1Jss55tiBmm2DOHUIGyA83U_orBYdTSRdTZNId67nbrKLWXCB09bAcsOn8Ue6xzQsuVS1RO-7AUDZtlhGYDl7fg_hW4A7OLTJYGAzP3Su6qkuFd6jFuYJhsi0PnNMp7DQCN3iVfhP5vwoVtoZ1fgfjKEYuAoMonviHmQHIvZWikgwkzlcew44-AofNk4sdNw1O-tSLJhaN5vTtg_vV0cUKG_Z6DJVXvK7ZBOyYyihYreimHD8ftU",
    description: "Un blanc agricole d'une intensité aromatique rare, distillé en colonne et reposé trois ans avant mise en bouteille. La pureté de la canne malgache à l'état brut.",
    nose: "Canne Verte & Agrumes",
    palate: "Vif & Minéral",
    finish: "Nette & Persistante",
    abv: "50% Alc/Vol",
    barrel: "Cuve Inox",
    origin: "Madagascar, Île Sainte-Marie",
    ageLabel: "3 Ans de Repos",
  },
  {
    id: 6,
    collection: "Réserve Impériale",
    name: "Dzama Nosy Boraha 20",
    price: 295,
    age: 20,
    sweetness: "honey-vanilla",
    exclusivity: 90,
    badge: null,
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBUTpAv4686Jgb26jBIjTCrZvcf7gdeC3dMjXTO-Ax9UKS3Sf4Th9fPG6AFxwyqLDt8GgLCLgFw38c0M9pUTKnEQ0NEmWRM2miOUV3Jpix_CA_8Ent8EvAfrOD9bPn4lDKnU2znisS4C-sGfuA7rwHc8q7zvK0Ho-_iovn402uwdobtIXhk9VIb7TJMg_yYgzlVCAaPBNer-UOEPnrhNAMBOWlaBwCHko0LpGzDywRss_lzEaQ4iS7zkfbxwcocIKl_bAtwxMxxYok",
    description: "Vingt ans d'océan Indien, de brise de vanille et d'ombre des forêts tropicales ont sculpté ce rhum d'exception, ambassadeur de l'île de Nosy Boraha dans toute sa splendeur.",
    nose: "Noix de Coco & Fleurs",
    palate: "Miel, Vanille & Bois Noble",
    finish: "Veloutée & Tropicale",
    abv: "44% Alc/Vol",
    barrel: "Ex-Sauternes, Chêne Français",
    origin: "Madagascar, Nosy Boraha",
    ageLabel: "20 Ans d'Âge",
  },
  {
    id: 7,
    collection: "Réserve Spéciale",
    name: "Dzama Grand Cru 15",
    price: 155,
    age: 15,
    sweetness: "balanced-oak",
    exclusivity: 80,
    badge: null,
    src: "/images/collections/vieux_rhum_15.jpeg",
    description: "Quinze ans d'un vieillissement rigoureux en fûts sélectionnés à la main par le Maître de Chai. Un équilibre magistral entre la générosité du terroir et la retenue du bois.",
    nose: "Tabac Blond & Cire d'Abeille",
    palate: "Chêne & Fruits Confits",
    finish: "Longue & Balsamique",
    abv: "43% Alc/Vol",
    barrel: "Chêne du Limousin, Double Fût",
    origin: "Madagascar, Côte Nord-Est",
    ageLabel: "15 Ans d'Âge",
  },
  {
    id: 8,
    collection: "Maître de Chai",
    name: "Dzama Orchidée Noire",
    price: 520,
    age: 30,
    sweetness: "honey-vanilla",
    exclusivity: 99,
    badge: { label: "Ultra Rare", color: "bg-secondary-container text-white" },
    src: "/images/collections/lucien_fohine_1984.jpeg",
    description: "Le couronnement de trente ans de patience absolue. Nommé en l'honneur de l'orchidée noire endémique de Madagascar, ce rhum est produit à moins de 200 flacons par an.",
    nose: "Orchidée, Truffe & Caramel",
    palate: "Opulent & Complexe",
    finish: "Infinie & Envoûtante",
    abv: "46% Alc/Vol",
    barrel: "Ex-Porto Vintage, Chêne Centenaire",
    origin: "Madagascar, Réserve Privée",
    ageLabel: "30 Ans — Production Limitée",
  },
  {
    id: 9,
    collection: "Cuvée Artisanale",
    name: "Dzama Épices Sauvages",
    price: 75,
    age: 8,
    sweetness: "dry-spicy",
    exclusivity: 65,
    badge: null,
    src: "/images/collections/amber_gold.jpeg",
    description: "Infusé aux épices sauvages de Madagascar — clou de girofle, poivre long et piment de la Jamaïque — ce rhum exprime la biodiversité aromatique de l'île avec une vigueur saisissante.",
    nose: "Clou de Girofle & Poivre",
    palate: "Épicé & Chaleureux",
    finish: "Longue & Aromatique",
    abv: "41% Alc/Vol",
    barrel: "Chêne Américain Toasté",
    origin: "Madagascar, Hauts Plateaux",
    ageLabel: "8 Ans d'Âge",
  },
  {
    id: 10,
    collection: "Cave Originelle",
    name: "Dzama Ambré 5 Ans",
    price: 55,
    age: 5,
    sweetness: "balanced-oak",
    exclusivity: 55,
    badge: null,
    src: "/images/collections/1.jpeg",
    description: "La porte d'entrée idéale dans l'univers Dzama. Cinq ans de vieillissement en cave confèrent à ce rhum ambré une rondeur accessible et une franchise aromatique désarmante.",
    nose: "Caramel & Bois Frais",
    palate: "Rond & Équilibré",
    finish: "Douce & Légèrement Épicée",
    abv: "40% Alc/Vol",
    barrel: "Chêne Américain",
    origin: "Madagascar, Nord",
    ageLabel: "5 Ans d'Âge",
  },
  {
    id: 11,
    collection: "Sélection Maison",
    name: "Dzama Caramel Brun",
    price: 95,
    age: 12,
    sweetness: "honey-vanilla",
    exclusivity: 72,
    badge: null,
    src: "/images/collections/5.jpeg",
    description: "Douze ans de maturation lente ont fondu les arômes de caramel brun et de vanille de Tahiti dans une texture soyeuse qui enveloppe le palais avec une générosité rare.",
    nose: "Caramel Beurre Salé & Vanille",
    palate: "Soyeux & Gourmand",
    finish: "Chaude & Persistante",
    abv: "43% Alc/Vol",
    barrel: "Ex-Sherry Oloroso",
    origin: "Madagascar, Côte Ouest",
    ageLabel: "12 Ans d'Âge",
  },
  {
    id: 12,
    collection: "Édition Classique",
    name: "Dzama Fût de Chêne",
    price: 70,
    age: 7,
    sweetness: "balanced-oak",
    exclusivity: 62,
    badge: null,
    src: "/images/collections/6.jpeg",
    description: "Un classique de la maison qui célèbre la noblesse du chêne. Sept ans de maturation en fûts de chêne blanc produisent un rhum structuré, droit et d'une fidélité remarquable.",
    nose: "Bois Blanc & Noisette",
    palate: "Structuré & Sec",
    finish: "Boisée & Nette",
    abv: "42% Alc/Vol",
    barrel: "Chêne Blanc Américain",
    origin: "Madagascar, Île Sainte-Marie",
    ageLabel: "7 Ans d'Âge",
  },
  {
    id: 13,
    collection: "Réserve du Domaine",
    name: "Dzama Prestige Noir",
    price: 210,
    age: 18,
    sweetness: "balanced-oak",
    exclusivity: 88,
    badge: { label: "Édition Limitée", color: "bg-primary-container text-on-primary" },
    src: "/images/collections/7.jpeg",
    description: "Dix-huit ans dans les ténèbres de la cave du domaine ont façonné un rhum d'un noir profond et d'une densité aromatique qui défie les conventions. Une édition confidentielle pour initiés.",
    nose: "Pruneaux & Café Torréfié",
    palate: "Dense & Concentré",
    finish: "Profonde & Tannique",
    abv: "47% Alc/Vol",
    barrel: "Ex-Bordeaux, Chêne Français",
    origin: "Madagascar, Domaine Privé",
    ageLabel: "18 Ans d'Âge",
  },
  {
    id: 14,
    collection: "Collection Florale",
    name: "Dzama Fleur Tropicale",
    price: 88,
    age: 9,
    sweetness: "honey-vanilla",
    exclusivity: 68,
    badge: null,
    src: "/images/collections/8.jpeg",
    description: "Vieilli neuf ans à proximité des plantations de ylang-ylang, ce rhum capte les effluves floraux uniques de Madagascar dans une expression délicate et d'une féminité affirmée.",
    nose: "Ylang-ylang & Jasmin",
    palate: "Floral & Soyeux",
    finish: "Légère & Parfumée",
    abv: "40% Alc/Vol",
    barrel: "Chêne Léger, Ex-Muscat",
    origin: "Madagascar, Région de Nosy Be",
    ageLabel: "9 Ans d'Âge",
  },
  {
    id: 15,
    collection: "Trésor de l'Île",
    name: "Dzama Réserve 1990",
    price: 780,
    age: 34,
    sweetness: "balanced-oak",
    exclusivity: 97,
    badge: { label: "Réserve Rare", color: "bg-secondary-container text-white" },
    src: "/images/collections/9.jpeg",
    description: "Trente-quatre ans après la récolte historique de 1990, ce rhum millésimé représente l'héritage vivant de Dzama. Chaque goutte contient l'histoire d'une île et d'une famille.",
    nose: "Vieux Cuir, Cigare & Figues",
    palate: "Enveloppant & Ancestral",
    finish: "Éternelle & Majestueuse",
    abv: "49% Alc/Vol",
    barrel: "Multi-fûts, Chêne Centenaire",
    origin: "Madagascar, Réserve Ancestrale",
    ageLabel: "Millésime 1990 — 34 Ans",
  },
];
